/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_auth_flavor (XDR *xdrs, auth_flavor *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_opaque_auth (XDR *xdrs, opaque_auth *objp)
{
	register int32_t *buf;

	 if (!xdr_auth_flavor (xdrs, &objp->flavor))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->body.body_val, (u_int *) &objp->body.body_len, 400))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_msg_type (XDR *xdrs, msg_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reply_stat (XDR *xdrs, reply_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_accept_stat (XDR *xdrs, accept_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reject_stat (XDR *xdrs, reject_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_auth_stat (XDR *xdrs, auth_stat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_call_body (XDR *xdrs, call_body *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = (decltype(buf)) XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->rpcvers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->proc))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->rpcvers);
		IXDR_PUT_U_LONG(buf, objp->prog);
		IXDR_PUT_U_LONG(buf, objp->vers);
		IXDR_PUT_U_LONG(buf, objp->proc);
		}
		 if (!xdr_opaque_auth (xdrs, &objp->cred))
			 return FALSE;
		 if (!xdr_opaque_auth (xdrs, &objp->verf))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = (decltype(buf)) XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->rpcvers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->prog))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->vers))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->proc))
				 return FALSE;

		} else {
		objp->rpcvers = IXDR_GET_U_LONG(buf);
		objp->prog = IXDR_GET_U_LONG(buf);
		objp->vers = IXDR_GET_U_LONG(buf);
		objp->proc = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_opaque_auth (xdrs, &objp->cred))
			 return FALSE;
		 if (!xdr_opaque_auth (xdrs, &objp->verf))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->rpcvers))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->prog))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->vers))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->proc))
		 return FALSE;
	 if (!xdr_opaque_auth (xdrs, &objp->cred))
		 return FALSE;
	 if (!xdr_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reply_body (XDR *xdrs, reply_body *objp)
{
	register int32_t *buf;

	 if (!xdr_reply_stat (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case reply_stat::MSG_ACCEPTED:
		 if (!xdr_accepted_reply (xdrs, &objp->reply_body_u.areply))
			 return FALSE;
		break;
	case reply_stat::MSG_DENIED:
		 if (!xdr_rejected_reply (xdrs, &objp->reply_body_u.rreply))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_rpc_mismatch_info (XDR *xdrs, rpc_mismatch_info *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->low))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->high))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_msg_body (XDR *xdrs, rpc_msg_body *objp)
{
	register int32_t *buf;

	 if (!xdr_msg_type (xdrs, &objp->mtype))
		 return FALSE;
	switch (objp->mtype) {
	case msg_type::CALL:
		 if (!xdr_call_body (xdrs, &objp->rpc_msg_body_u.cbody))
			 return FALSE;
		break;
	case msg_type::REPLY:
		 if (!xdr_reply_body (xdrs, &objp->rpc_msg_body_u.rbody))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_rpc_reply_data (XDR *xdrs, rpc_reply_data *objp)
{
	register int32_t *buf;

	 if (!xdr_accept_stat (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case accept_stat::SUCCESS:
		 if (!xdr_opaque (xdrs, objp->rpc_reply_data_u.results, 0))
			 return FALSE;
		break;
	case accept_stat::PROG_MISMATCH:
		 if (!xdr_rpc_mismatch_info (xdrs, &objp->rpc_reply_data_u.mismatch_info))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_rpc_msg (XDR *xdrs, rpc_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->xid))
		 return FALSE;
	 if (!xdr_rpc_msg_body (xdrs, &objp->body))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_accepted_reply (XDR *xdrs, accepted_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_opaque_auth (xdrs, &objp->verf))
		 return FALSE;
	 if (!xdr_rpc_reply_data (xdrs, &objp->reply_data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rejected_reply (XDR *xdrs, rejected_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_reject_stat (xdrs, &objp->stat))
		 return FALSE;
	switch (objp->stat) {
	case reject_stat::RPC_MISMATCH:
		 if (!xdr_rpc_mismatch_info (xdrs, &objp->rejected_reply_u.mismatch_info))
			 return FALSE;
		break;
	case reject_stat::AUTH_ERROR:
		 if (!xdr_auth_stat (xdrs, &objp->rejected_reply_u.astat))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_authsys_parms (XDR *xdrs, authsys_parms *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->stamp))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->machinename, 255))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gid))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->gids.gids_val, (u_int *) &objp->gids.gids_len, 16,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}
